services:
  frontend:
    build: ../frontend
    container_name: apartments_frontend
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ../backend
    container_name: apartments_backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    depends_on:
      - mongo
    volumes:
      - ../backend/uploads:/app/uploads
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: apartments_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
